/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.105
 * Generated at: 2020-09-08 07:40:57 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.account;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.freewinesearcher.common.Dbutil;
import com.freewinesearcher.batch.Spider;
import java.io.*;
import java.text.*;
import java.lang.*;
import java.sql.*;
import com.freewinesearcher.common.Wine;
import com.freewinesearcher.online.Webroutines;
import com.freewinesearcher.common.Wineset;

public final class createaccount_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<title>Create an account on Vinopedia</title>\r\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/header2.jsp", out, false);
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t\r\n");
      out.write("\t");

		String username = Webroutines.filterUserInput(request.getParameter("username"));
		String password = request.getParameter("password");
		String password2 = request.getParameter("password2");
		String email = Webroutines.filterUserInput(request.getParameter("email"));
		String message = Webroutines.filterUserInput(request.getParameter("message"));
		String action = Webroutines.filterUserInput(request.getParameter("action"));
		if (action == null)
			action = "";
		if (username == null)
			username = "";
		if (password == null)
			password = "";
		if (password2 == null)
			password2 = "";
		if (email == null)
			email = "";
		boolean showform = true;
		boolean ok = true;
		boolean success = false;
		message = "";
		if (action.equals("newaccount")) {
			if (!password.equals(password2)) {
				ok = false;
				message += "The password and the verification are not the same! ";
			} else if (password.length() < 5) {
				ok = false;
				message += "The password should be at least 5 characters long. ";
			} else if (username.length() < 5) {
				ok = false;
				message += "The username should be at least 5 characters long. ";
			}
			/* else if (Dbutil.readValueFromDB("select * from vp_users where user_id='"+Spider.SQLEscape("username")+"';","id")!=null){
				ok=false;
				message+="A user with that name already exists. If you have forgotten your password please <a href='/account/lostpassword.jsp'>cick here</a> to reset it. otherwise, please choose a different username. ";
			}  */
			else if (!Webroutines.checkEmail(email)) {
				ok = false;
				message += "Your email address is not valid, please correct it. ";
			}
			if (ok) {
				showform = false;
				Webroutines.adduser(username, password, email);
				success = true;
				message = "Your account Registration has been successfull";
			}
		}
		if (showform) {
	
      out.write("\r\n");
      out.write("\t<form action=\"\" method=\"post\">\r\n");
      out.write("\t\tTo create an account on Vinopedia, please supply a username, password\r\n");
      out.write("\t\tand a working email address. We will send an account activation email\r\n");
      out.write("\t\tfor verification before activating the account.<br />\r\n");
      out.write("\t\t");
      out.print(message);
      out.write("\r\n");
      out.write("\t\t<table>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td>Username</td>\r\n");
      out.write("\t\t\t\t<td><input type=\"text\" name=\"username\" value=\"");
      out.print(username);
      out.write("\" /></td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td>Password</td>\r\n");
      out.write("\t\t\t\t<td><input type=\"password\" name=\"password\" value=\"\" /></td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td>Confirm Password</td>\r\n");
      out.write("\t\t\t\t<td><input type=\"password\" name=\"password2\" value=\"\" /></td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td>Email address</td>\r\n");
      out.write("\t\t\t\t<td><input type=\"text\" name=\"email\" value=\"");
      out.print(email);
      out.write("\" /></td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t</table>\r\n");
      out.write("\t\t<input type='hidden' name='action' value='newaccount' /> <input\r\n");
      out.write("\t\t\ttype=\"submit\" value=\"submit\" />\r\n");
      out.write("\t</form>\r\n");
      out.write("\t");

		}
	
      out.write('\r');
      out.write('\n');
      out.write('	');

		if (success) {
	
      out.write('\r');
      out.write('\n');
      out.write('	');
      out.print(message);
      out.write('\r');
      out.write('\n');
      out.write('	');

		}
	
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
