/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.105
 * Generated at: 2020-09-08 07:26:36 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.settings;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.freewinesearcher.online.Auditlogger;
import com.freewinesearcher.common.Context;
import com.freewinesearcher.common.Wijnzoeker;
import java.util.ArrayList;
import java.util.List;
import com.freewinesearcher.online.Translator;
import com.freewinesearcher.online.PageHandler;
import com.freewinesearcher.common.Shop;
import java.util.Iterator;
import java.util.ListIterator;
import java.io.*;
import java.text.*;
import java.lang.*;
import java.sql.*;
import com.freewinesearcher.common.Wine;
import com.freewinesearcher.common.Wineset;
import com.freewinesearcher.batch.Spider;
import com.freewinesearcher.common.datafeeds.DataFeed;
import com.freewinesearcher.batch.FeedScraper;
import com.freewinesearcher.online.Webroutines;
import com.freewinesearcher.batch.TableScraper;
import org.apache.commons.fileupload.*;
import org.apache.commons.fileupload.servlet.ServletFileUpload;
import org.apache.commons.fileupload.disk.DiskFileItemFactory;
import org.apache.commons.io.FilenameUtils;
import java.util.*;
import java.io.File;
import java.lang.Exception;
import com.freewinesearcher.common.Variables;
import com.freewinesearcher.common.Dbutil;
import com.freewinesearcher.online.Ad;
import com.freewinesearcher.online.PageHandler;
import com.freewinesearcher.online.Webroutines;
import com.freewinesearcher.common.Configuration;
import java.util.HashSet;
import com.freewinesearcher.online.PageHandler;
import com.freewinesearcher.online.Webroutines;
import com.freewinesearcher.common.Dbutil;
import com.freewinesearcher.common.Configuration;
import com.freewinesearcher.common.Configuration;
import com.freewinesearcher.online.PageHandler;
import com.freewinesearcher.common.Dbutil;

public final class editdatafeed_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(4);
    _jspx_dependants.put("/snippets/topbar.jsp", Long.valueOf(1598006156000L));
    _jspx_dependants.put("/snippets/textpage.jsp", Long.valueOf(1598006156000L));
    _jspx_dependants.put("/snippets/footer.jsp", Long.valueOf(1598006156000L));
    _jspx_dependants.put("/snippets/logoandsearch.jsp", Long.valueOf(1598006156000L));
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD XHTML 1.0 Transitional//EN\" \"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<html><head>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      com.freewinesearcher.online.Searchdata searchdata = null;
      synchronized (session) {
        searchdata = (com.freewinesearcher.online.Searchdata) _jspx_page_context.getAttribute("searchdata", javax.servlet.jsp.PageContext.SESSION_SCOPE);
        if (searchdata == null){
          searchdata = new com.freewinesearcher.online.Searchdata();
          _jspx_page_context.setAttribute("searchdata", searchdata, javax.servlet.jsp.PageContext.SESSION_SCOPE);
        }
      }
      out.write('\r');
      out.write('\n');
      com.freewinesearcher.common.datafeeds.DataFeed datafeed = null;
      synchronized (session) {
        datafeed = (com.freewinesearcher.common.datafeeds.DataFeed) _jspx_page_context.getAttribute("datafeed", javax.servlet.jsp.PageContext.SESSION_SCOPE);
        if (datafeed == null){
          datafeed = new com.freewinesearcher.common.datafeeds.DataFeed();
          _jspx_page_context.setAttribute("datafeed", datafeed, javax.servlet.jsp.PageContext.SESSION_SCOPE);
        }
      }
      out.write('\r');
      out.write('\n');
      org.apache.jasper.runtime.JspRuntimeLibrary.introspecthelper(_jspx_page_context.findAttribute("datafeed"), "assume75cl", "false", null, null, false);
      out.write('\r');
      out.write('\n');
      org.apache.jasper.runtime.JspRuntimeLibrary.introspect(_jspx_page_context.findAttribute("datafeed"), request);
      out.write("\r\n");
      out.write("\r\n");
      out.write("<title>Edit data feed</title>\r\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/header2.jsp", out, false);
      out.write("\r\n");
      out.write("</head><body>\r\n");
	
	//DataFeed storeddatafeed=(DataFeed)session.getAttribute("datafeed");
	//if (storeddatafeed!=null&&storeddatafeed.feedContent!=null) datafeed.feedContent=storeddatafeed.feedContent;
	PageHandler p=PageHandler.getInstance(request,response,"Edit Data Feed");
	Shop shop=null;
	String savemessage="";
	Wineset wineset=null;
	String feederrors="";
	boolean readyforsave=false;
	long wsid=0;
	try {wsid = Integer.parseInt(request.getParameter("wsid"));}catch (Exception e){}
	long shopid=0;
	try {shopid = Integer.parseInt(request.getParameter("shopid"));}catch (Exception e){}
	String actie = request.getParameter("action");
    if (actie==null) actie="";
    if (session.getAttribute("shop")!=null) shop=(Shop)session.getAttribute("shop");
 	if (Webroutines.getShopFromUserId(request.getRemoteUser())>0) {
 		if (shop==null) shop=new Shop(Webroutines.getShopFromUserId(request.getRemoteUser()));
 		if (!datafeed.validfeed) {
 			String url=datafeed.getUrl();
 			datafeed=DataFeed.getDataFeed(new Context(request),shop.shopid,0);
 			if (datafeed==null) datafeed=new DataFeed(url);
 		}
 		if (datafeed==null) {
 			datafeed=new DataFeed();
 		} else if (datafeed.validfeed){
 			datafeed.parse();
 		}
 	}
 	if (actie!=null&&actie.equals("Retrieve")&&(request.isUserInRole("Moderators")||request.isUserInRole("admin"))) {
		int id=0;
		try{id=Integer.parseInt(request.getParameter("shopid"));}catch(Exception e){}
		if (id>0)shop=new Shop(id);    	
		datafeed=DataFeed.getDataFeed(new Context(request),shop.shopid,0);
		datafeed.parse();
	}
   
	String encoding="";
    if (encoding.equals("")) encoding="iso-8859-1";
    ArrayList<String> countries = Webroutines.getCountries();
	String countrycode = request.getParameter("countrycode");
    if (countrycode!=null&&shop!=null){
    	shop.countrycode=countrycode;
    	shop.country=Webroutines.getCountryFromCode(countrycode);
    }
    ArrayList<String> currencies = Webroutines.getCurrency();
    String linkurl = request.getParameter("linkurl");
    if (linkurl==null) linkurl="";
    if (!linkurl.equals("")&&!linkurl.toLowerCase().startsWith("http")) linkurl="http://"+linkurl;
    if (!linkurl.equals("")&&shop!=null){
    	shop.linkurl=linkurl;
    }
    String currency = request.getParameter("currency");
    if (currency!=null&&shop!=null){
    	shop.currency=currency;
    }
    int vat=-1;
    try{vat=Integer.parseInt(request.getParameter("vat"));}catch(Exception e){}
    if (vat>-1&&shop!=null) shop.exvat=vat;
    if (ServletFileUpload.isMultipartContent(request)){
    	datafeed=new DataFeed(request);
    	if (datafeed.format.equals(DataFeed.formats.Elmar)){
    		shop=new Shop(datafeed.getUrl());
			session.setAttribute("shop",shop);
			datafeed=shop.datafeed;
    	}
    }
    
    
    if (actie!=null&&actie.equals("Analyze")) {
     	shop=null;	
     	session.setAttribute("shop",shop);
    	datafeed=new DataFeed(datafeed.getUrl());    
    	if (datafeed.format.equals(DataFeed.formats.Elmar)){
    		shop=new Shop(datafeed.getUrl());
			session.setAttribute("shop",shop);
			datafeed=shop.datafeed;
    	}
    	Auditlogger al;
    	al=(Auditlogger)session.getAttribute("auditlogger");
    	if (al==null) al=new Auditlogger(request);
    	if (shop!=null&&!al.isUserAuthorized(shop.shopid,request)){
    		al.setAction("Datafeed denied "+actie+" "+shop.ShopConfigUrl);
    		al.setObjecttype("Data feed");
    		al.logaction();
    		shop=null;
    		datafeed=new DataFeed();
    		datafeed.urlstatus=DataFeed.urlstatusses.DuplicateURL;
    	} else {
    		al.setAction("Datafeed "+actie+" "+(shop==null?datafeed.getUrl():shop.ShopConfigUrl));
    		al.setObjecttype("Datafeed feed");
    		al.logaction();
    	}
    	
    }
    if (datafeed!=null&&datafeed.urlstatus==DataFeed.urlstatusses.OK&&datafeed.feedstatus==DataFeed.feedstatusses.OK){
    	readyforsave=true;
    	if (shop==null){
	     	wineset=datafeed.getWines(0,"[Your shop name]",null,1.0,1.0,100,true);
     	} else {
     		wineset=datafeed.getWines(shop.shopid,shop.shopname,null,1.0,1.0,100,true);
     		
     	}
    	feederrors=datafeed.checkWineset(wineset);
    	if (!feederrors.equals("")) readyforsave=false;
    	if (datafeed.url.equals("")) {
    		readyforsave=false;
    		feederrors+="You can only save the datafeed when it is available at a url, not if you uploaded it from your PC (which is just for testing).";
    	}
     	
    	
    }
	session.setAttribute("shop",shop);
	session.setAttribute("datafeed",datafeed);
    	
    	
    	
	if (actie.equals("Saved")){
		out.write("The data feed has been saved. From tomorrow, the wines will be shown on Vinopedia.");
	} else {

      out.write('\r');
      out.write('\n');
 request.setAttribute("ad","false"); 
      out.write('\r');
      out.write('\n');
 request.setAttribute("numberofimages","-1"); 
      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
	int numberofimages=2;
	try {numberofimages=Integer.parseInt((String)request.getAttribute("numberofimages"));}catch (Exception e){}
 
      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
 //PageHandler p=(PageHandler)request.getAttribute("pagehandler");
      out.write('\r');
      out.write('\n');
 String mobilelink="/m";
 if (PageHandler.getInstance(request,response).thispage.contains("/wine/")){
	 mobilelink=PageHandler.getInstance(request,response).thispage.replace("/wine/","/mwine/");
 } else if (PageHandler.getInstance(request,response).thispage.contains("/winery/")){
	 mobilelink=PageHandler.getInstance(request,response).thispage.replace("/winery/","/mwinery/");
 } else if (PageHandler.getInstance(request,response).thispage.contains("/region/")){
	 mobilelink=PageHandler.getInstance(request,response).thispage.replace("/region/","/mregion/");
 } else {
	mobilelink="/mobile.jsp"+(PageHandler.getInstance(request,response).searchdata.getName().length()>2?"?name="+Webroutines.URLEncode(Webroutines.removeAccents(PageHandler.getInstance(request,response).searchdata.getName()))+(PageHandler.getInstance(request,response).searchdata.getVintage().length()>3?"+"+PageHandler.getInstance(request,response).searchdata.getVintage():"").trim():"");
 }

      out.write("\r\n");
      out.write("<div class='topbar spriter spriter-refine'>\r\n");
      out.write("<div class='topbarcontent'><img src='");
      out.print(Configuration.static2prefix );
      out.write("/css/sprite4.png' style='display:none;width:1px;height:1px' alt=''/><img src='");
      out.print(Configuration.cdnprefix );
      out.write("/css/spriter.png' style='display:none;width:1px;height:1px' alt=''/>\r\n");
      out.write("<div id='mobile'>\r\n");
      out.write("<a href=\"");
      out.print(mobilelink);
      out.write("\">Mobile access</a>\r\n");
      out.write("<a href='");
      out.print((request.getAttribute("wineguidelink")==null?"/nf/wine-guide/":request.getAttribute("wineguidelink")));
      out.write("' rel='nofollow'>Wine Guide</a>\r\n");
      out.write("<a href='/settings/index.jsp' rel='nofollow'>PriceAlerts</a>\r\n");
      out.write("<a href='/retailers.jsp' rel='nofollow'>Getting listed</a>\r\n");
      out.write("<a href='/about.jsp' rel='nofollow'>About us</a>\r\n");
      out.write("<a href='/links.jsp' rel='nofollow'>Links</a>\r\n");
      out.write("<a href='/publishers.jsp' rel='nofollow'>For web site owners</a>\r\n");
      out.write("<!-- <a href='/Deals.jsp' rel='nofollow'>Deals</a> -->\r\n");
if (request.getRemoteUser()!=null) {
      out.write("<a href='/settings/index.jsp?logoff=true'>Log off</a>");
} 
      out.write("\r\n");
      out.write("</div>\r\n");
if (false){ 
      out.write("\r\n");
      out.write("<!-- \r\n");
      out.write("<div id='language'>");
      out.print(PageHandler.getInstance(request,response).t.get("language"));
      out.write(": \r\n");
      out.write("<a href='/lang-EN/wine/");
      out.print((Webroutines.URLEncode(PageHandler.getInstance(request,response).searchdata.getName()).replace("'","&apos;")+(PageHandler.getInstance(request,response).searchdata.getVintage().length()>3?"?vintage=" + PageHandler.getInstance(request,response).searchdata.getVintage():"")));
      out.write("'><img alt='English' src='/images/transparent.gif' class='sprite sprite-language sprite-english'/></a>\r\n");
      out.write("<a href='/lang-FR/wine/");
      out.print((Webroutines.URLEncode(PageHandler.getInstance(request,response).searchdata.getName()).replace("'","&apos;")+(PageHandler.getInstance(request,response).searchdata.getVintage().length()>3?"?vintage=" + PageHandler.getInstance(request,response).searchdata.getVintage():"")));
      out.write("'><img alt='Français' src='/images/transparent.gif' class='sprite sprite-language sprite-french'/></a>\r\n");
      out.write("<a href='/lang-NL/wine/");
      out.print((Webroutines.URLEncode(PageHandler.getInstance(request,response).searchdata.getName()).replace("'","&apos;")+(PageHandler.getInstance(request,response).searchdata.getVintage().length()>3?"?vintage=" + PageHandler.getInstance(request,response).searchdata.getVintage():"")));
      out.write("'><img alt='Nederlands' src='/images/transparent.gif' class='sprite sprite-language sprite-dutch'/></a>\r\n");
      out.write("</div>\r\n");
      out.write(" -->");
} 
      out.write("\r\n");
      out.write("&nbsp;\r\n");
      out.write("</div>\r\n");
      out.write("</div>");
      out.write("\r\n");
      out.write("<div class='textpage'>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<div class='logoandsearch' id='logoandsearch'>\r\n");
      out.write("\t\t<div class='logo'><a href=\"/\" title=\"Wine Searcher and Wine Prices Comparison\"><img src='");
      out.print(Configuration.cdnprefix);
      out.write("/css2/logo.png' alt='Vinopedia Wine Searcher and Price Comparison'/></a></div>\r\n");
      out.write("\t\t<div class='search'>\r\n");
      out.write("\t\t<div class='findwine'>");
      out.print(PageHandler.getInstance(request,response).t.get("searchwine"));
      out.write("</div>\r\n");
      out.write("\t\t\t");
// <img class='searchgosmall' alt='Search' src='/css2/gosmall.jpg' onclick='document.getElementById("searchform").submit()' />
      out.write("\r\n");
      out.write("\t\t\t<form action='");
      out.print(PageHandler.getInstance(request,response).searchpage);
      out.write("' method=\"post\" id=\"searchform\" name=\"searchform\" accept-charset=\"UTF-8\"><input type=\"hidden\" name=\"dosearch\" value=\"true\" /><input class='searchinput' id='name' type='text' name=\"name\" value=\"");
      out.print(Webroutines.escape((PageHandler.getInstance(request,response).searchdata.getName()+" "+PageHandler.getInstance(request,response).searchdata.getVintage()).trim()));
      out.write("\" size=\"25\" /></form>\r\n");
      out.write("\t\t\t<div class='sprite sprite-gosmall searchgosmall' onclick='document.getElementById(\"searchform\").submit()' ></div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("</div>\r\n");
 // <div id='plusone'><script type='text/javascript' defer="defer">/*<![CDATA[*/document.write('<g:plusone href="<%=PageHandler.getInstance(request,response).plusonelink % >"></g:plusone>');/*]]>*/</script></div>

      out.write('\r');
      out.write('\n');
 if (numberofimages>0){ 
      out.write("\r\n");
      out.write("<div id='right'>");

	String imagepath="/images/photos/";
 	HashSet<String> images=Webroutines.getRandomImages(application.getRealPath("/")+imagepath,numberofimages);
	int n=0;
 	for (String filename:images){
		n++;
		out.write("<img class='photo' src='"+imagepath+filename+"' alt='"+filename+"'/>");
	}
	if ("true".equals(request.getAttribute("ad"))){
	Ad rightad = new Ad("newdesign",160, 600, PageHandler.getInstance(request,response).hostcountry, PageHandler.getInstance(request,response).s.wineset.region, PageHandler.getInstance(request,response).s.wineset.knownwineid,"");
	out.write(rightad.html);
	}
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("<div id='left'>\t\r\n");
} else {	
      out.write("\r\n");
      out.write("\r\n");
} 
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
 if (request.isUserInRole("admin")){ 
	ArrayList<String> shops = Webroutines.getShopListWithDatafeed();
      out.write("\r\n");
      out.write("\t<form action=\"editdatafeed.jsp\" method=\"get\">Shop\r\n");
      out.write("\t<select name=\"shopid\" >\r\n");
      out.write("\t");
 for (int i=0;i<shops.size();i=i+2){
      out.write("\r\n");
      out.write("\t\t<option value=\"");
      out.print(shops.get(i));
      out.write('"');
      out.write('>');
      out.print(shops.get(i+1));
      out.write("</option>\r\n");
      out.write("\t");
}
      out.write("\r\n");
      out.write("\t</select>\r\n");
      out.write("\t<input type=\"hidden\" name=\"wsid\" value=\"");
      out.print(wsid );
      out.write("\"/>\r\n");
      out.write("\t<input type=\"hidden\" name=\"action\" value=\"Retrieve\"/>\r\n");
      out.write("\t<input type=\"submit\" value=\"Retrieve\"/>\r\n");
      out.write("\t</form>\r\n");
} 
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<h1>Configure a data feed</h1>\r\n");
      out.write("\r\n");
      out.write("    \r\n");
      out.write("On this page you can configure and test your data feed. You can enter the URL of your data feed if it is available on your server. Or you can upload a feed as a file, but in that case you cannot save it (this is for testing purposes only. If the data feed can be processes you must make it available on a server so we can download it daily).\r\n");
      out.write("<br/><br/>\r\n");
      out.write("<table><tr><td>\r\n");
      out.write("<form name=\"formOne\"\r\n");
      out.write("\taction=\"editdatafeed.jsp\" METHOD=\"POST\"\r\n");
      out.write("\tid=\"formOne\">\r\n");
      out.write("\t\r\n");
      out.write("\t<input type=\"hidden\" name=\"wsid\" value=\"");
      out.print(wsid );
      out.write("\"/>\r\n");
      out.write("Data feed url (internet address)<br/>\r\n");
      out.write("<input type='text' name='url' value='");
      out.print((datafeed!=null?datafeed.getUrl():""));
      out.write("'\tsize='50'/><input type=\"hidden\" name=\"action\" id=\"actie\" value=\"Analyze\"/> \r\n");
      out.write("<input type=\"submit\" name=\"submitButton\" value=\"Load data feed\"/><br/>\r\n");
if (!savemessage.equals("")) out.write("<font color='red'>"+savemessage+"</font><br/>");
      out.write('\r');
      out.write('\n');
 out.write("<font color='red'>"+datafeed.getUrlStatusMessage()+"</font><br/>");
      out.write("\r\n");
      out.write("(If your shop supports <a href='http://projekt.wifo.uni-mannheim.de/elmar/nav?dest=impl.shopsystems.index&rid=26' target='_blank'>Elmar</a>, please enter the url of the shopinfo.xml file.)<br/>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</form>\r\n");
      out.write("</td><td>\r\n");
      out.write("<form action=\"editdatafeed.jsp\" method=\"post\" enctype=\"multipart/form-data\">\r\n");
      out.write("Upload a data feed<br/>\r\n");
      out.write("\t  <input name=\"myFile\" type=\"file\" />\r\n");
      out.write("\t  <input type=\"submit\" value=\"Upload\" />\r\n");
      out.write("\t</form>\r\n");
      out.write("</td></tr></table>\t\r\n");
      out.write("\t\r\n");
      out.write("<br/>\r\n");
if (datafeed.urlstatus.equals(DataFeed.urlstatusses.OK)){ 
	if (!datafeed.feedstatus.equals(DataFeed.feedstatusses.OK)){
      out.write("\t\r\n");
      out.write("\t<h3>Feed could not be read</h3>\r\n");
      out.write("\t");
      out.print(datafeed.getFeedStatusMessage());
      out.write("<br/><br/>\r\n");
      out.write("<form action='/contact.jsp'>\r\n");
      out.write("Email address: <input type='text' name='email' size='100' />\r\n");
      out.write("<input type='hidden' name= 'site' value='");
      out.print(((shop==null||shop.shopurl==null)?datafeed.getUrl():shop.shopurl).replaceAll("'","&apos;"));
      out.write("'/>\r\n");
      out.write("<input type='hidden' name='captcha' value='nocheck'/>\r\n");
      out.write("<input type='hidden' name='formsent' value='sent'/>\r\n");
      out.write("<input type='hidden' name='message' value='A merchant reported a problem with a datafeed.'/>\r\n");
      out.write("<input type='submit' value='Send' />\r\n");
      out.write("</form>\r\n");
} else {
      out.write("\r\n");
      out.write("\r\n");
      out.write("<h2>Review and test data feed</h2>\r\n");
      out.write("Your data feed was recognized as ");
      out.print(datafeed.format);
      out.write(" <strong>but has not yet been saved</strong>. Below you should review the results and change the settings, so the wine name, bottle size etc. are displayed correctly. After testing it you can go on to step 4 (entering your company information) by pressing the button below the configuration editor.\r\n");
      out.write("<form id=\"feedconfig\" action=\"editdatafeed.jsp\" method=\"post\">\r\n");
      out.write("<input type=\"hidden\" name=\"wsid\" value=\"");
      out.print(wsid );
      out.write("\"/>\r\n");
      out.write("<h2>Data feed configuration editor</h2>\r\n");
      out.write("We need to know how to find the different types of information in the data feed. \"Wine name\" should contain all information to identify an individual wine, including producer and region. You can select more than one field; the wine name as it is shown to the users will be composed of the different fields in the order you specify.<br/>\r\n");
      out.write("For the other types of information such as vintage and price, you can also select more than one field; only the first suitable match is selected if the fields contain different data.<br/>\r\n");
      out.write("Note: you can select the same field for different types of information. For instance: if a \"description\" field contains the name and the vintage, you select that field for both wine name and vintage.<br/><br/>\r\n");
      out.write("<table >\r\n");
      out.write("<tr><th width='230px'>Information</th>");
for (int i=1;i<=datafeed.maxlabels;i++) out.write("<th>Field "+i+"</th>"); 
      out.write("</tr>\r\n");
      out.write("<tr><td>Wine name</td>");
      out.print(datafeed.getSelectBox("name") );
      out.write("<td>");
if (datafeed.getNameorder()[0].equals("")) out.write("<font color='Red'>Please select one or more fields</font>"); 
      out.write("</td></tr>\r\n");
      out.write("<tr><td>Vintage</td>");
      out.print(datafeed.getSelectBox("vintage") );
      out.write("<td>");
if (datafeed.getVintageorder()[0].equals("")) out.write("<font color='Red'>Please select one or more fields</font>"); 
      out.write("</td></tr>\r\n");
      out.write("<tr><td>Price</td>");
      out.print(datafeed.getSelectBox("price") );
      out.write("<td>");
if (datafeed.getPriceorder()[0].equals("")) out.write("<font color='Red'>Please select one or more fields</font>"); 
      out.write("</td></tr>\r\n");
      out.write("<tr><td>Product url</td>");
      out.print(datafeed.getSelectBox("url") );
      out.write("<td>");
if (datafeed.getUrlorder()[0].equals("")) out.write("<font color='Red'>Please select one or more fields with a product link. If no product link is in the feed, the general URL of the shop will be used.</font>"); 
      out.write("</td></tr>\r\n");
      out.write("<tr><td>Bottle size</td>");
      out.print(datafeed.getSelectBox("size") );
      out.write("<td>");
if (datafeed.getSizeorder()[0].equals("")) out.write("<font color='Red'>Please select one or more fields</font>"); 
      out.write("</td></tr>\r\n");
      out.write("<tr><td colspan='1'>Assume 75cl when no size is found?</td><td><input type='checkbox' name='assume75cl' ");
      out.print((datafeed.assume75cl?" checked='checked' ":""));
      out.write("/></td><td colspan='2'></td></tr>\r\n");
      out.write("</table>\r\n");
 out.write (datafeed.assume75cl||wineset.records!=datafeed.wineswithsize?(!datafeed.assume75cl&&wineset.records>2*datafeed.wineswithsize?"<font color='red'>The bottle size was found for only ":"The bottle size was found for ")+datafeed.wineswithsize+" of in total "+wineset.records+" wines."+(!datafeed.assume75cl&&wineset.records>2*datafeed.wineswithsize?" If for normal bottles (75cl) no size is given in the datafeed, please mark the checkbox. </font>":(datafeed.assume75cl?" If no bottle size is found, a size of 75cl is taken (this is not yet shown in the result list below).":"")+" Only mark the checkbox if the data feed contains no size indication for 75cl bottles.<br/>"):""); 
      out.write("\r\n");
      out.write("<font color='red'>");
      out.print(feederrors);
      out.write("<br/></font>\r\n");
      out.write("<br/><br/><table><tr><td><input type=\"submit\" name='action' value=\"Test\"><input type=\"hidden\" name=\"wsid\" value=\"");
      out.print(wsid );
      out.write('"');
      out.write('/');
      out.write('>');
if (wsid>0){ 
      out.write("\t<input type=\"hidden\" name=\"shopid\" value=\"");
      out.print(shopid );
      out.write("\"/>\r\n");
      out.write("\t");
} 
      out.write("</form></td><td>\r\n");
      out.write("<script language=\"JavaScript\" type=\"text/javascript\">\r\n");
      out.write("function shopinfo(){\r\n");
      out.write("\tdocument.getElementById(\"feedconfig\").action='/settings/editshopinfo.jsp?test';\r\n");
      out.write("\tdocument.getElementById(\"feedconfig\").submit();\r\n");
      out.write("\t\r\n");
      out.write("}\r\n");
      out.write("document.write('<input type=\"button\" onclick=\"javascript:shopinfo()\" name=\"action\" value=\"Step 4: Company details\" ");
if (!readyforsave) out.write ("disabled=\"true\""); 
      out.write("/></td></tr></table>');\r\n");
      out.write("</script>\r\n");
      out.write("<noscript><form action=\"/settings/editshopinfo.jsp\" method=\"post\" ><input type=\"hidden\" name=\"wsid\" value=\"");
      out.print(wsid );
      out.write('"');
      out.write('/');
      out.write('>');
if (wsid>0) {
      out.write("\t<input type=\"hidden\" name=\"shopid\" value=\"");
      out.print(shopid );
      out.write("\"/>\r\n");
      out.write("\t");
} 
      out.write("<input type=\"submit\" name='action' value=\"Step 4: Company details\" ");
if (!readyforsave) out.write ("disabled='true'"); 
      out.write("/></form></td></tr></table>\r\n");
      out.write("\t\r\n");
      out.write("Please make sure you test your settings after making changes, otherwise they will not be saved!<br/></noscript>\r\n");
if (!readyforsave) {
      out.write("\r\n");
      out.write("Before you can go to the next screen (shop details), you must correct the following issues:<br/>\r\n");
      out.print(feederrors );
      out.write('\r');
      out.write('\n');
} else if (new Context(request).userid.equals("")){

      out.write("Note: you must log in in order to save data feeds. If you have no account yet, click <a href=\"/forum/user/insert.page\" target='_blank'>here</a> to create one.\r\n");
}
      out.write("\r\n");
      out.write("<h2>Data feed content</h2>\r\n");
      out.write("The data feed contains the following information:<br/><br/>\r\n");
      out.write("<div style=\"overflow:auto; max-height:250px; width:900px;border-style:solid\">\r\n");
out.write(datafeed.toHTML()); 
      out.write("\r\n");
      out.write("</div><br/>\r\n");
      out.write("<h2>Data feed results</h2>\r\n");
      out.write("In the table below you can see the results of the datafeed editor. Please check if all fields are filled correctly and make any necessary changes in the configuration table above. If all fields are filled correctly, you can go to step 4: company details. There you can change the shop name and currency and save the data feed.<br/><br/>\r\n");
      out.write("<form action=\"/settings/editshopinfo.jsp\" method=\"post\"><input type=\"submit\" name='action' value=\"Step 4: Company details\" ");
if (!readyforsave) out.write ("disabled='true'"); 
      out.write("/></form></td></tr></table>\r\n");


	out.write(Webroutines.getTabbedWineResultsHTML(wineset,new Translator(),searchdata,99999,response,"false",false,"editdatafeed.jsp",p.s.singlevintage,null,true,false));
      out.write('\r');
      out.write('\n');
      out.write('	');
}//datafeed!=null
}//feedcontent>0
}//saved
      out.write('	');
      out.write('\r');
      out.write('\n');
 
	PageHandler.getInstance(request,response).getLogger().logaction();
	session.setAttribute("lasturl",PageHandler.getInstance(request,response).thispage);
	String canonicallink=(String)request.getAttribute("canonicallink");
	String regionlink=(String)request.getAttribute("regionlink");
	if (regionlink==null) regionlink="<a href='/region/'>Wines by region</a>";

      out.write("<div class='footer'><div id='links'><a href='/' rel='nofollow'>Home</a><a href='/links.jsp' rel='nofollow'>Links</a><a href='/contact.jsp' rel='nofollow'>Contact Vinopedia</a><a href='/about.jsp' rel='nofollow'>About us</a><a href='/termsofuse.jsp' rel='nofollow'>Terms of use</a>");
      out.print(regionlink);
 if (canonicallink!=null) out.write("<br/>"+canonicallink); 
      out.write("</div>\r\n");
      out.write("<div class='clear'></div><div id='copyright'>&#169; ");
      out.print(java.util.GregorianCalendar.getInstance().get(java.util.GregorianCalendar.YEAR));
      out.write(" Vinopedia.com</div></div>");

PageHandler.getInstance(request,response).firstrequest=false;
PageHandler.getInstance(request,response).cleanup();
//for (Cookie cookie:request.getCookies()) { 
//	if (cookie.getName().equals("wineid")||cookie.getName().equals("sort")||cookie.getName().equals("vintage")) {cookie.setMaxAge(0);response.addCookie(cookie);}
//}
 
      out.write("\t\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
