/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.105
 * Generated at: 2020-09-08 07:26:19 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.freewinesearcher.online.Webroutines;
import com.freewinesearcher.online.PageHandler;
import com.freewinesearcher.common.Knownwines;
import com.freewinesearcher.common.Dbutil;
import com.freewinesearcher.common.Configuration;
import com.freewinesearcher.common.Configuration;

public final class header2_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/snippets/jsincludes.jsp", Long.valueOf(1598006156000L));
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\n');

	//if (request.getServerName().toLowerCase().contains("searchasaservice")&&!request.getServletPath().toLowerCase().contains("searchasaservice")) {
	//	response.sendRedirect("/searchasaservice.jsp");
	//	return;
	//}
	String originalurl = (String) request.getAttribute("originalURL");
	if (Configuration.detectSuspectedBot) {
		String ua = request.getHeader("user-agent");
		if (ua == null) {
			ua = "";
		}
		ua = ua.toLowerCase();
		boolean mobile = false;
		if (!mobile && ua.contains("iphone")) {
			mobile = true;
		}
		if (!mobile && ua.contains("ppc;")) {
			mobile = true;
		}
		if (!mobile && ua.contains("windows ce")) {
			mobile = true;
		}
		if (!mobile && ua.contains("mobile")) {
			mobile = true;
		}
		if (!mobile && ua.contains("midp")) {
			mobile = true;
		}
		if (!mobile && ua.contains("smartphone")) {
			mobile = true;
		}
		if (!mobile && ua.contains("android")) {
			mobile = true;
		}
		if (mobile && ua.contains("ipad;")) {
			mobile = false;
		}
		if (originalurl != null && (originalurl.contains("/mwine/") || originalurl.contains("/mregion/")
				|| originalurl.contains("/mwinery/"))) {
			mobile = true;
		}

		int botstatus = PageHandler.getInstance(request, response).getBotstatus();
		if (!mobile && botstatus >= 2) {
			Dbutil.logger.info("header2.jsp botstatus=" + botstatus + " called, should not happen. IP="
					+ PageHandler.getInstance(request, response).ipaddress);
			response.setStatus(302);
			response.setHeader("Location", "/check.jsp?targeturl=" + Webroutines.URLEncodeUTF8(originalurl));
			response.setHeader("Connection", "close");
			return;
		}
	} else {
		PageHandler.getInstance(request, response).botstatus = 0;
	}

	try {
		if (originalurl == null)
			originalurl = "";
		String querystring = (String) request.getAttribute("originalQueryString");

		if (querystring == null || querystring.equals("")) {
			querystring = "";
		} else {
			querystring = "?" + querystring;
		}
		if (querystring.contains("width")) {
			Dbutil.logger.info("Width in url " + originalurl + "" + querystring);
			Dbutil.logger
					.info("IP: " + request.getRemoteAddr() + ", Referrer: " + request.getHeader("Referer"));
		}

		if (originalurl.contains("/winery/") || originalurl.contains("/store/")
				|| originalurl.contains("/wine-guide/") || originalurl.contains("/region/")) {
			response.setHeader("Cache-Control", "max-age=3600");
		} //HTTP 1.1
			//response.setHeader("Pragma","no-cache"); //HTTP 1.0
		response.setDateHeader("Expires", 0); //prevents caching at the proxy server

		if (PageHandler.getInstance(request, response).abuse) {
			response.setStatus(403);

      if (true) {
        _jspx_page_context.forward("abuse.jsp");
        return;
      }
      out.write('\n');

	return;
		}
		if (originalurl.contains("/region/")
				&& (originalurl.contains(" ") || originalurl.contains("%20") || !originalurl.endsWith("/"))) {
			String newurl = originalurl.replaceAll(" ", "+").replaceAll("%20", "+");
			if (!newurl.endsWith("/"))
				newurl += "/";
			response.setStatus(301);
			response.setHeader("Location", newurl);
			response.setHeader("Connection", "close");
			return;
		}
		if (originalurl.contains("https://") && request.getRemoteUser() == null
				&& (!originalurl.contains("/admin") && !originalurl.contains("/settings")
						&& !originalurl.contains("/moderator") && !originalurl.contains("thankyou"))) {
			String newurl = originalurl.replace("https://", "http://");
			response.setStatus(301);
			response.setHeader("Location", newurl);
			response.setHeader("Connection", "close");
			return;
		}
		//(!Webroutines.getRegexPatternValue("([^%_-]\\d\\d\\d\\d)$",originalurl).equals("")&&!querystring.contains("vintage"))
		if (originalurl.contains("/wine/") && (originalurl.contains("%20") || !Webroutines
				.removeAccents(request.getParameter("name")).equals(request.getParameter("name")))) {
			String originalvintage = Webroutines.getRegexPatternValue("(?:%20| |\\+)(\\d\\d\\d\\d)$",
					originalurl);
			if (request.getHeader("Referrer") != null && request.getHeader("Referrer").contains("vinopedia"))
				Dbutil.logger.info("URL " + originalurl + " found on " + request.getHeader("Referrer"));
			String redurl = "/wine/"
					+ Webroutines.URLEncode(Webroutines.removeAccents(request.getParameter("name")))
					+ (querystring.length() > 1 ? querystring : "");
			if (originalvintage.length() > 0)
				redurl = redurl.replaceAll("\\+" + originalvintage, "") + "+" + originalvintage;
			response.setStatus(301);
			response.setHeader("Location", redurl);
			response.setHeader("Connection", "close");
			return;
		}
		if (originalurl.contains("/wine/") && querystring.startsWith("?vintage")
				&& querystring.length() == 13) {
			String originalvintage = Webroutines.getRegexPatternValue("(\\d\\d\\d\\d)$", querystring);
			if (request.getHeader("Referrer") != null && request.getHeader("Referrer").contains("vinopedia"))
				Dbutil.logger.info("URL " + originalurl + " found on " + request.getHeader("Referrer"));
			String redurl = "/wine/"
					+ Webroutines.URLEncode(Webroutines.removeAccents(request.getParameter("name")));
			if (originalvintage.length() > 0)
				redurl = redurl + "+" + originalvintage;
			response.setStatus(301);
			response.setHeader("Location", redurl);
			response.setHeader("Connection", "close");
			return;
		}
		if (originalurl.contains("/wine/"))
			try {
				int reqvintage = Integer.parseInt(
						Webroutines.getRegexPatternValue("(?:%20| |\\+)(\\d\\d\\d\\d)$", originalurl));
				if (reqvintage > Configuration.thisyear) {
					String redurl = "/wine/"
							+ Webroutines.URLEncode(Webroutines.removeAccents(request.getParameter("name")))
							+ (querystring.length() > 1 ? querystring : "");
					redurl = redurl.replaceAll("\\+" + reqvintage, "");
					response.setStatus(301);
					response.setHeader("Location", redurl);
					response.setHeader("Connection", "close");
				}
			} catch (Exception e) {
			}

		if (request.getParameter("logoff") != null) {
			response.sendRedirect("/logout.jsp");
			return;
		}

		if (originalurl.contains("freewinesearcher") && !originalurl.contains("wine2/")) {
			String newurl = originalurl.replace("freewinesearcher", "vinopedia") + querystring;
			session.setAttribute("fws", "true");
			response.setStatus(301);
			response.setHeader("Location", newurl);
			response.setHeader("Connection", "close");
			return;
		}
	} catch (Exception e) {
		Dbutil.logger.error("Exception in header2.jsp", e);
	}
	if (!PageHandler.getInstance(request, response).block
			&& !PageHandler.getInstance(request, response).abuse) {

      out.write('\n');

	if (!"Y".equals(Webroutines.filterUserInput(request.getParameter("print")))) {

      out.write("<link rel=\"stylesheet\" type=\"text/css\"\n");
      out.write("\thref=\"");
      out.print(request.isSecure() ? Configuration.securestylesheet : Configuration.stylesheet);
      out.write("\" />\n");

	} else {

      out.write("<link rel=\"stylesheet\" type=\"text/css\" media=\"print\" href=\"/print.css\" />\n");

	}

      out.write('\n');

	if (false && !"".equals(PageHandler.getInstance(request, response).plusonelink)) {

      out.write("<script type=\"text/javascript\">\n");
      out.write("\t(function() {\n");
      out.write("\t\tvar po = document.createElement('script');\n");
      out.write("\t\tpo.type = 'text/javascript';\n");
      out.write("\t\tpo.async = true;\n");
      out.write("\t\tpo.src = 'https://apis.google.com/js/plusone.js';\n");
      out.write("\t\tvar s = document.getElementsByTagName('script')[0];\n");
      out.write("\t\ts.parentNode.insertBefore(po, s);\n");
      out.write("\t})();\n");
      out.write("</script>\n");

	}

      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html;charset=ISO-8859-1\" />\n");

	if ((originalurl.contains("/index.jsp") && !originalurl.contains("wine-guide")
				&& !originalurl.contains("/store/") || originalurl.contains("/external.jsp")
				|| originalurl.contains("/winelinks.jsp"))) {

      out.write("<meta name=\"robots\" content=\"noindex,nofollow\" />\n");

	} else if (originalurl.contains("/wine2")) {

      out.write("<meta name=\"robots\" content=\"noindex,nofollow\" />\n");

	} else if (originalurl.contains("topwines")) {

      out.write("<meta name=\"robots\" content=\"noindex,follow\" />\n");

	} else {

      out.write("<meta name=\"robots\" content=\"index,follow\" />\n");

	}

      out.write("<link rel=\"icon\" type=\"image/png\"\n");
      out.write("\thref=\"");
      out.print(Configuration.staticprefix);
      out.write("/favicon.png\" />");
      out.write("<script type=\"text/javascript\" src=\"http://ajax.googleapis.com/ajax/libs/jquery/1.6.1/jquery.min.js\" ></script><script type=\"text/javascript\" src=\"");
      out.print(request.isSecure()?"":Configuration.static2prefix);
      out.write("/js/combinedjs4.js?version=25\" defer=\"defer\"></script><script type=\"text/javascript\">function doonload(){document.getElementById('name').focus();$(\"#resulttabs\").tabs(\"#gspanes  > div.pan\", {tabs:'a.resulttab'});if($(\"#resulttabs\").data(\"tabs\")&&$(\"#resulttabs\").data(\"tabs\").getCurrentTab().attr(\"href\")=='#map') showmap();}</script>");
      out.write('\n');

	}

      out.write("\n");
      out.write("\n");
      out.write("<!-- Google Analytics -->\n");
      out.write("<script>\n");
      out.write("\t(function(i, s, o, g, r, a, m) {\n");
      out.write("\t\ti['GoogleAnalyticsObject'] = r;\n");
      out.write("\t\ti[r] = i[r] || function() {\n");
      out.write("\t\t\t(i[r].q = i[r].q || []).push(arguments)\n");
      out.write("\t\t}, i[r].l = 1 * new Date();\n");
      out.write("\t\ta = s.createElement(o), m = s.getElementsByTagName(o)[0];\n");
      out.write("\t\ta.async = 1;\n");
      out.write("\t\ta.src = g;\n");
      out.write("\t\tm.parentNode.insertBefore(a, m)\n");
      out.write("\t})(window, document, 'script', '//www.google-analytics.com/analytics.js',\n");
      out.write("\t\t\t'ga');\n");
      out.write("\n");
      out.write("\tga('create', 'UA-1788182-2', 'auto', {\n");
      out.write("\t\t'legacyCookieDomain' : 'vinopedia.com'\n");
      out.write("\t});\n");
      out.print(PageHandler.getInstance(request, response).asyncGAtracking);
      out.write("\n");
      out.write("\tga('send', 'pageview');\n");
      out.write("</script>\n");
      out.write("<!-- End Google Analytics -->\n");
      out.write("\n");
      out.write("<script src=\"//load.sumome.com/\"\n");
      out.write("\tdata-sumo-site-id=\"acdd8ce37b7f36678940878463b273d4ff0c2a4bfa21ae34571c8b2fe3614ca6\"\n");
      out.write("\tasync=\"async\"></script>\n");
      out.write("<!-- Quantcast Tag -->\n");
      out.write("<script type=\"text/javascript\">\n");
      out.write("\tvar _qevents = _qevents || [];\n");
      out.write("\n");
      out.write("\t(function() {\n");
      out.write("\t\tvar elem = document.createElement('script');\n");
      out.write("\t\telem.src = (document.location.protocol == \"https:\" ? \"https://secure\"\n");
      out.write("\t\t\t\t: \"http://edge\")\n");
      out.write("\t\t\t\t+ \".quantserve.com/quant.js\";\n");
      out.write("\t\telem.async = true;\n");
      out.write("\t\telem.type = \"text/javascript\";\n");
      out.write("\t\tvar scpt = document.getElementsByTagName('script')[0];\n");
      out.write("\t\tscpt.parentNode.insertBefore(elem, scpt);\n");
      out.write("\t})();\n");
      out.write("\n");
      out.write("\t_qevents.push({\n");
      out.write("\t\tqacct : \"p-_LkbUtSUQgFCM\"\n");
      out.write("\t});\n");
      out.write("</script>\n");
      out.write("\n");
      out.write("<noscript>\n");
      out.write("\t<div style=\"display: none;\">\n");
      out.write("\t\t<img src=\"//pixel.quantserve.com/pixel/p-_LkbUtSUQgFCM.gif\" border=\"0\"\n");
      out.write("\t\t\theight=\"1\" width=\"1\" alt=\"Quantcast\" />\n");
      out.write("\t</div>\n");
      out.write("</noscript>\n");
      out.write("<!-- End Quantcast tag -->");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
