/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.105
 * Generated at: 2020-09-08 07:25:56 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.freewinesearcher.online.Webroutines;
import com.freewinesearcher.online.Searchdata;
import com.freewinesearcher.online.PageHandler;
import com.freewinesearcher.online.SearchHandler;
import com.freewinesearcher.online.Ad;
import com.freewinesearcher.common.Knownwines;
import com.freewinesearcher.common.PerformanceLogger;
import com.freewinesearcher.common.Configuration;
import com.freewinesearcher.online.Hemabox;
import com.freewinesearcher.online.RecommendationAd;
import com.freewinesearcher.online.Webroutines;
import com.freewinesearcher.online.PageHandler;
import com.freewinesearcher.common.Knownwines;
import com.freewinesearcher.common.Dbutil;
import com.freewinesearcher.common.Configuration;
import com.freewinesearcher.common.Configuration;
import com.freewinesearcher.common.Configuration;
import com.freewinesearcher.online.PageHandler;
import com.freewinesearcher.online.Hemabox;
import com.freewinesearcher.online.Webroutines;
import com.freewinesearcher.common.Dbutil;
import com.freewinesearcher.online.PageHandler;
import com.freewinesearcher.online.Webroutines;
import com.freewinesearcher.common.Configuration;
import com.freewinesearcher.online.PageHandler;
import com.freewinesearcher.common.Dbutil;
import com.freewinesearcher.online.PageHandler;
import com.freewinesearcher.online.Webroutines;
import com.freewinesearcher.common.Configuration;
import com.freewinesearcher.online.PageHandler;
import com.freewinesearcher.online.Webroutines;
import com.freewinesearcher.common.Dbutil;
import com.freewinesearcher.common.Configuration;
import com.freewinesearcher.common.Configuration;
import com.freewinesearcher.online.PageHandler;
import com.freewinesearcher.common.Dbutil;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(7);
    _jspx_dependants.put("/snippets/topbar.jsp", Long.valueOf(1598006156000L));
    _jspx_dependants.put("/snippets/footer.jsp", Long.valueOf(1598006156000L));
    _jspx_dependants.put("/header2.jsp", Long.valueOf(1598006154000L));
    _jspx_dependants.put("/snippets/bigsearchbar.jsp", Long.valueOf(1598006156000L));
    _jspx_dependants.put("/snippets/logoandsearch.jsp", Long.valueOf(1598006156000L));
    _jspx_dependants.put("/snippets/jsincludes.jsp", Long.valueOf(1598006156000L));
    _jspx_dependants.put("/snippets/tips.jsp", Long.valueOf(1598006156000L));
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');

	PerformanceLogger pl = new PerformanceLogger();
	pl.log("Start index.jsp");
	long start = System.currentTimeMillis();
	boolean debuglog = false;

	PageHandler p = PageHandler.getInstance(request, response, "Search");

	if ("sneak preview".equalsIgnoreCase(request.getParameter("name"))) {
		session.setAttribute("testmode", true);
		Dbutil.logger.info("testmode");
	}

	debuglog = false;

	pl.log("Start processSearchdata");
	p.searchdata.sponsoredresults = true;
	p.searchpage = "/index.jsp";
	p.processSearchdata(request);
	pl.log("End processSearchData");
	if (p.s != null && p.s.singlevintage > 0)
		p.getLogger().vintage = p.s.singlevintage + "";
	String originaltesturl = (String) request.getAttribute("originalURL");
	if (request.getAttribute("originalURL") != null
			&& ((String) request.getAttribute("originalURL")).contains("/wine2/") && p.s != null
			&& p.s.wineset != null && p.s.wineset.canonicallink != null
			&& p.s.wineset.canonicallink.length() > 0) {
		String newurl = p.s.wineset.canonicallink;
		response.setStatus(301);
		response.setHeader("Location", newurl);
		response.setHeader("Connection", "close");
		return;
	}

      out.write("<!DOCTYPE HTML>");
      com.freewinesearcher.online.Searchdata searchdata = null;
      synchronized (session) {
        searchdata = (com.freewinesearcher.online.Searchdata) _jspx_page_context.getAttribute("searchdata", javax.servlet.jsp.PageContext.SESSION_SCOPE);
        if (searchdata == null){
          searchdata = new com.freewinesearcher.online.Searchdata();
          _jspx_page_context.setAttribute("searchdata", searchdata, javax.servlet.jsp.PageContext.SESSION_SCOPE);
        }
      }
      com.freewinesearcher.online.Searchhistory searchhistory = null;
      synchronized (session) {
        searchhistory = (com.freewinesearcher.online.Searchhistory) _jspx_page_context.getAttribute("searchhistory", javax.servlet.jsp.PageContext.SESSION_SCOPE);
        if (searchhistory == null){
          searchhistory = new com.freewinesearcher.online.Searchhistory();
          _jspx_page_context.setAttribute("searchhistory", searchhistory, javax.servlet.jsp.PageContext.SESSION_SCOPE);
        }
      }
      out.write("<html>\r\n");
      out.write("<head>");
      out.write('\n');

	//if (request.getServerName().toLowerCase().contains("searchasaservice")&&!request.getServletPath().toLowerCase().contains("searchasaservice")) {
	//	response.sendRedirect("/searchasaservice.jsp");
	//	return;
	//}
	String originalurl = (String) request.getAttribute("originalURL");
	if (Configuration.detectSuspectedBot) {
		String ua = request.getHeader("user-agent");
		if (ua == null) {
			ua = "";
		}
		ua = ua.toLowerCase();
		boolean mobile = false;
		if (!mobile && ua.contains("iphone")) {
			mobile = true;
		}
		if (!mobile && ua.contains("ppc;")) {
			mobile = true;
		}
		if (!mobile && ua.contains("windows ce")) {
			mobile = true;
		}
		if (!mobile && ua.contains("mobile")) {
			mobile = true;
		}
		if (!mobile && ua.contains("midp")) {
			mobile = true;
		}
		if (!mobile && ua.contains("smartphone")) {
			mobile = true;
		}
		if (!mobile && ua.contains("android")) {
			mobile = true;
		}
		if (mobile && ua.contains("ipad;")) {
			mobile = false;
		}
		if (originalurl != null && (originalurl.contains("/mwine/") || originalurl.contains("/mregion/")
				|| originalurl.contains("/mwinery/"))) {
			mobile = true;
		}

		int botstatus = PageHandler.getInstance(request, response).getBotstatus();
		if (!mobile && botstatus >= 2) {
			Dbutil.logger.info("header2.jsp botstatus=" + botstatus + " called, should not happen. IP="
					+ PageHandler.getInstance(request, response).ipaddress);
			response.setStatus(302);
			response.setHeader("Location", "/check.jsp?targeturl=" + Webroutines.URLEncodeUTF8(originalurl));
			response.setHeader("Connection", "close");
			return;
		}
	} else {
		PageHandler.getInstance(request, response).botstatus = 0;
	}

	try {
		if (originalurl == null)
			originalurl = "";
		String querystring = (String) request.getAttribute("originalQueryString");

		if (querystring == null || querystring.equals("")) {
			querystring = "";
		} else {
			querystring = "?" + querystring;
		}
		if (querystring.contains("width")) {
			Dbutil.logger.info("Width in url " + originalurl + "" + querystring);
			Dbutil.logger
					.info("IP: " + request.getRemoteAddr() + ", Referrer: " + request.getHeader("Referer"));
		}

		if (originalurl.contains("/winery/") || originalurl.contains("/store/")
				|| originalurl.contains("/wine-guide/") || originalurl.contains("/region/")) {
			response.setHeader("Cache-Control", "max-age=3600");
		} //HTTP 1.1
			//response.setHeader("Pragma","no-cache"); //HTTP 1.0
		response.setDateHeader("Expires", 0); //prevents caching at the proxy server

		if (PageHandler.getInstance(request, response).abuse) {
			response.setStatus(403);

      if (true) {
        _jspx_page_context.forward("abuse.jsp");
        return;
      }
      out.write('\n');

	return;
		}
		if (originalurl.contains("/region/")
				&& (originalurl.contains(" ") || originalurl.contains("%20") || !originalurl.endsWith("/"))) {
			String newurl = originalurl.replaceAll(" ", "+").replaceAll("%20", "+");
			if (!newurl.endsWith("/"))
				newurl += "/";
			response.setStatus(301);
			response.setHeader("Location", newurl);
			response.setHeader("Connection", "close");
			return;
		}
		if (originalurl.contains("https://") && request.getRemoteUser() == null
				&& (!originalurl.contains("/admin") && !originalurl.contains("/settings")
						&& !originalurl.contains("/moderator") && !originalurl.contains("thankyou"))) {
			String newurl = originalurl.replace("https://", "http://");
			response.setStatus(301);
			response.setHeader("Location", newurl);
			response.setHeader("Connection", "close");
			return;
		}
		//(!Webroutines.getRegexPatternValue("([^%_-]\\d\\d\\d\\d)$",originalurl).equals("")&&!querystring.contains("vintage"))
		if (originalurl.contains("/wine/") && (originalurl.contains("%20") || !Webroutines
				.removeAccents(request.getParameter("name")).equals(request.getParameter("name")))) {
			String originalvintage = Webroutines.getRegexPatternValue("(?:%20| |\\+)(\\d\\d\\d\\d)$",
					originalurl);
			if (request.getHeader("Referrer") != null && request.getHeader("Referrer").contains("vinopedia"))
				Dbutil.logger.info("URL " + originalurl + " found on " + request.getHeader("Referrer"));
			String redurl = "/wine/"
					+ Webroutines.URLEncode(Webroutines.removeAccents(request.getParameter("name")))
					+ (querystring.length() > 1 ? querystring : "");
			if (originalvintage.length() > 0)
				redurl = redurl.replaceAll("\\+" + originalvintage, "") + "+" + originalvintage;
			response.setStatus(301);
			response.setHeader("Location", redurl);
			response.setHeader("Connection", "close");
			return;
		}
		if (originalurl.contains("/wine/") && querystring.startsWith("?vintage")
				&& querystring.length() == 13) {
			String originalvintage = Webroutines.getRegexPatternValue("(\\d\\d\\d\\d)$", querystring);
			if (request.getHeader("Referrer") != null && request.getHeader("Referrer").contains("vinopedia"))
				Dbutil.logger.info("URL " + originalurl + " found on " + request.getHeader("Referrer"));
			String redurl = "/wine/"
					+ Webroutines.URLEncode(Webroutines.removeAccents(request.getParameter("name")));
			if (originalvintage.length() > 0)
				redurl = redurl + "+" + originalvintage;
			response.setStatus(301);
			response.setHeader("Location", redurl);
			response.setHeader("Connection", "close");
			return;
		}
		if (originalurl.contains("/wine/"))
			try {
				int reqvintage = Integer.parseInt(
						Webroutines.getRegexPatternValue("(?:%20| |\\+)(\\d\\d\\d\\d)$", originalurl));
				if (reqvintage > Configuration.thisyear) {
					String redurl = "/wine/"
							+ Webroutines.URLEncode(Webroutines.removeAccents(request.getParameter("name")))
							+ (querystring.length() > 1 ? querystring : "");
					redurl = redurl.replaceAll("\\+" + reqvintage, "");
					response.setStatus(301);
					response.setHeader("Location", redurl);
					response.setHeader("Connection", "close");
				}
			} catch (Exception e) {
			}

		if (request.getParameter("logoff") != null) {
			response.sendRedirect("/logout.jsp");
			return;
		}

		if (originalurl.contains("freewinesearcher") && !originalurl.contains("wine2/")) {
			String newurl = originalurl.replace("freewinesearcher", "vinopedia") + querystring;
			session.setAttribute("fws", "true");
			response.setStatus(301);
			response.setHeader("Location", newurl);
			response.setHeader("Connection", "close");
			return;
		}
	} catch (Exception e) {
		Dbutil.logger.error("Exception in header2.jsp", e);
	}
	if (!PageHandler.getInstance(request, response).block
			&& !PageHandler.getInstance(request, response).abuse) {

      out.write('\n');

	if (!"Y".equals(Webroutines.filterUserInput(request.getParameter("print")))) {

      out.write("<link rel=\"stylesheet\" type=\"text/css\"\n");
      out.write("\thref=\"");
      out.print(request.isSecure() ? Configuration.securestylesheet : Configuration.stylesheet);
      out.write("\" />\n");

	} else {

      out.write("<link rel=\"stylesheet\" type=\"text/css\" media=\"print\" href=\"/print.css\" />\n");

	}

      out.write('\n');

	if (false && !"".equals(PageHandler.getInstance(request, response).plusonelink)) {

      out.write("<script type=\"text/javascript\">\n");
      out.write("\t(function() {\n");
      out.write("\t\tvar po = document.createElement('script');\n");
      out.write("\t\tpo.type = 'text/javascript';\n");
      out.write("\t\tpo.async = true;\n");
      out.write("\t\tpo.src = 'https://apis.google.com/js/plusone.js';\n");
      out.write("\t\tvar s = document.getElementsByTagName('script')[0];\n");
      out.write("\t\ts.parentNode.insertBefore(po, s);\n");
      out.write("\t})();\n");
      out.write("</script>\n");

	}

      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html;charset=ISO-8859-1\" />\n");

	if ((originalurl.contains("/index.jsp") && !originalurl.contains("wine-guide")
				&& !originalurl.contains("/store/") || originalurl.contains("/external.jsp")
				|| originalurl.contains("/winelinks.jsp"))) {

      out.write("<meta name=\"robots\" content=\"noindex,nofollow\" />\n");

	} else if (originalurl.contains("/wine2")) {

      out.write("<meta name=\"robots\" content=\"noindex,nofollow\" />\n");

	} else if (originalurl.contains("topwines")) {

      out.write("<meta name=\"robots\" content=\"noindex,follow\" />\n");

	} else {

      out.write("<meta name=\"robots\" content=\"index,follow\" />\n");

	}

      out.write("<link rel=\"icon\" type=\"image/png\"\n");
      out.write("\thref=\"");
      out.print(Configuration.staticprefix);
      out.write("/favicon.png\" />");
      out.write("<script type=\"text/javascript\" src=\"http://ajax.googleapis.com/ajax/libs/jquery/1.6.1/jquery.min.js\" ></script><script type=\"text/javascript\" src=\"");
      out.print(request.isSecure()?"":Configuration.static2prefix);
      out.write("/js/combinedjs4.js?version=25\" defer=\"defer\"></script><script type=\"text/javascript\">function doonload(){document.getElementById('name').focus();$(\"#resulttabs\").tabs(\"#gspanes  > div.pan\", {tabs:'a.resulttab'});if($(\"#resulttabs\").data(\"tabs\")&&$(\"#resulttabs\").data(\"tabs\").getCurrentTab().attr(\"href\")=='#map') showmap();}</script>");
      out.write('\n');

	}

      out.write("\n");
      out.write("\n");
      out.write("<!-- Google Analytics -->\n");
      out.write("<script>\n");
      out.write("\t(function(i, s, o, g, r, a, m) {\n");
      out.write("\t\ti['GoogleAnalyticsObject'] = r;\n");
      out.write("\t\ti[r] = i[r] || function() {\n");
      out.write("\t\t\t(i[r].q = i[r].q || []).push(arguments)\n");
      out.write("\t\t}, i[r].l = 1 * new Date();\n");
      out.write("\t\ta = s.createElement(o), m = s.getElementsByTagName(o)[0];\n");
      out.write("\t\ta.async = 1;\n");
      out.write("\t\ta.src = g;\n");
      out.write("\t\tm.parentNode.insertBefore(a, m)\n");
      out.write("\t})(window, document, 'script', '//www.google-analytics.com/analytics.js',\n");
      out.write("\t\t\t'ga');\n");
      out.write("\n");
      out.write("\tga('create', 'UA-1788182-2', 'auto', {\n");
      out.write("\t\t'legacyCookieDomain' : 'vinopedia.com'\n");
      out.write("\t});\n");
      out.print(PageHandler.getInstance(request, response).asyncGAtracking);
      out.write("\n");
      out.write("\tga('send', 'pageview');\n");
      out.write("</script>\n");
      out.write("<!-- End Google Analytics -->\n");
      out.write("\n");
      out.write("<script src=\"//load.sumome.com/\"\n");
      out.write("\tdata-sumo-site-id=\"acdd8ce37b7f36678940878463b273d4ff0c2a4bfa21ae34571c8b2fe3614ca6\"\n");
      out.write("\tasync=\"async\"></script>\n");
      out.write("<!-- Quantcast Tag -->\n");
      out.write("<script type=\"text/javascript\">\n");
      out.write("\tvar _qevents = _qevents || [];\n");
      out.write("\n");
      out.write("\t(function() {\n");
      out.write("\t\tvar elem = document.createElement('script');\n");
      out.write("\t\telem.src = (document.location.protocol == \"https:\" ? \"https://secure\"\n");
      out.write("\t\t\t\t: \"http://edge\")\n");
      out.write("\t\t\t\t+ \".quantserve.com/quant.js\";\n");
      out.write("\t\telem.async = true;\n");
      out.write("\t\telem.type = \"text/javascript\";\n");
      out.write("\t\tvar scpt = document.getElementsByTagName('script')[0];\n");
      out.write("\t\tscpt.parentNode.insertBefore(elem, scpt);\n");
      out.write("\t})();\n");
      out.write("\n");
      out.write("\t_qevents.push({\n");
      out.write("\t\tqacct : \"p-_LkbUtSUQgFCM\"\n");
      out.write("\t});\n");
      out.write("</script>\n");
      out.write("\n");
      out.write("<noscript>\n");
      out.write("\t<div style=\"display: none;\">\n");
      out.write("\t\t<img src=\"//pixel.quantserve.com/pixel/p-_LkbUtSUQgFCM.gif\" border=\"0\"\n");
      out.write("\t\t\theight=\"1\" width=\"1\" alt=\"Quantcast\" />\n");
      out.write("\t</div>\n");
      out.write("</noscript>\n");
      out.write("<!-- End Quantcast tag -->");
      out.write("<title>\r\n");
      out.write("\t");

		if (!p.searchdata.getName().equals("")) {
			out.print((request.isUserInRole("admin") && p.s.wineset.knownwineid > 0
					? p.s.wineset.knownwineid + " "
					: "")
					+ (p.s.wineset.knownwineid > 0
							? Knownwines.getKnownWineName(p.s.wineset.knownwineid)
							: p.searchdata.getName().replaceAll("^\\d\\d\\d\\d\\d\\d ", ""))
									.replaceAll("^Ch.teau ", "").replaceAll("&", "&amp;")
					+ (p.s.singlevintage > 0 ? " " + p.s.singlevintage : "") + " Prices");
		} else {
			//out.print("Vinopedia.com Wine Search and Price Comparison - Buy wine online");
			out.print("Wine Search and Price Comparison - Vinopedia.com");
		}
	
      out.write("\r\n");
      out.write("</title>\r\n");

	session.setAttribute("winename",
			(p.s.wineset.knownwineid > 0
					? Knownwines.getKnownWineName(p.s.wineset.knownwineid)
					: searchdata.getName()).replaceAll("^\\d\\d\\d\\d\\d\\d ", ""));
	String headerwinename = "";
	if (PageHandler.getInstance(request, response).s != null
			&& PageHandler.getInstance(request, response).s.wineset != null) {
		headerwinename = Webroutines
				.escape(PageHandler.getInstance(request, response).s.wineset.knownwineid > 0
						? Knownwines.getKnownWineName(
								PageHandler.getInstance(request, response).s.wineset.knownwineid)
						: PageHandler.getInstance(request, response).searchdata.getName())
				.replaceAll("^\\d\\d\\d\\d\\d\\d ", "")
				+ (p.s.singlevintage > 0 ? " " + p.s.singlevintage : "");
	}
	if (!PageHandler.getInstance(request, response).searchdata.getName().equals("")) {
		out.print("<meta name=\"keywords\" content=\"");
		for (int i = 0; i < headerwinename.split("\\s+").length; i++) {
			out.print(headerwinename.split("\\s+")[i] + ", ");
		}
		out.print("buy " + headerwinename + ", Parker ratings, wine price, buy wine\" />");
	} else {
		out.print(
				"<meta name=\"keywords\" content=\"buy wine, wine online, wine guide, price, wine searcher\" />");
	}
	if ("NL".equals(PageHandler.getInstance(request, response).searchdata.getLanguage())) {
		if (!headerwinename.equals("") && PageHandler.getInstance(request, response).s != null) {
			out.write("<meta name=\"description\" content=\""
					+ PageHandler.getInstance(request, response).t.get("pricecomparisonfor") + " "
					+ headerwinename + " (" + PageHandler.getInstance(request, response).s.wineset.records
					+ " aanbiedingen gevonden)\" />");
		} else {
			out.write(
					"<meta name=\"description\" content=\"De meest complete gratis prijsvergelijkingssite van wijnen in Europa.\" />");
		}

	} else {
		if (!headerwinename.equals("") && PageHandler.getInstance(request, response).s != null) {
			out.write("<meta name=\"description\" content=\""
					+ (PageHandler.getInstance(request, response).s.wineset.records > 4
							? "Compare " + PageHandler.getInstance(request, response).s.wineset.records
									+ " online offers for " + headerwinename + ", "
							: "Price comparison for " + headerwinename + ", ")
					+ "Parker and Wine Spectator ratings, the best vintages and background information.\" />");
		} else {
			out.print(
					"<meta name=\"description\" content=\"See where you can buy your favorite wine online, ratings, the best vintages and background info.\" />");
		}

	}

      out.write('\r');
      out.write('\n');

	pl.log("Start header");

      out.write('\r');
      out.write('\n');

	if (p.s.wineset.canonicallink != null && !p.s.wineset.canonicallink.equals("")) {

      out.write("<link rel=\"canonical\" href=\"");
      out.print(p.s.wineset.canonicallink);
      out.write("\" />\r\n");

	}
	//if (false){ //Apparently, mobile detection does not work for Google bot
	if (!p.bot && p.firstrequest && p.mobile) {
		String newloc = "/m";
		try {
			if (PageHandler.getInstance(request, response).s.wineset.knownwineid > 0)
				newloc = "/mwine/" + Webroutines
						.URLEncode((PageHandler.getInstance(request, response).searchdata.getName() + " "
								+ PageHandler.getInstance(request, response).searchdata.getVintage()).trim());
		} catch (Exception e) {
		}

		if (newloc != null && !newloc.equals("")) {
			//Dbutil.logger.info("Redirecting to mobile page: "+request.getHeader("user-agent"));
			response.setStatus(302);
			response.setHeader("Location", newloc);
			response.setHeader("Connection", "close");
			return;
		}
	}
	//}

      out.write("<meta name=\"verify-v1\"\r\n");
      out.write("\tcontent=\"DPurn9ZNRpI1pXuOlIigNqJ6JoMePo97QY0m2L3eBrA=\" />\r\n");
      out.write("<meta name=\"google-site-verification\"\r\n");
      out.write("\tcontent=\"_fzJ24glka7UkSftFW4UhkGseJvlVn4Wa-zA7r6N5VM\" />\r\n");
      out.write("</head>\r\n");
      out.write("<body onload=\"javascript:doonload();\">\r\n");
      out.write("\t");

		if (!PageHandler.getInstance(request, response).block
				&& !PageHandler.getInstance(request, response).abuse) {
			if (!p.s.search || p.s.wineset == null) {
				// No search
	
      out.write("<div class='topbar spriter spriter-refine'>\r\n");
      out.write("\t\t<div class='topbarcontent'>\r\n");
      out.write("\t\t\t<img src='");
      out.print(Configuration.staticprefix);
      out.write("/css/sprite4.png' alt=''\r\n");
      out.write("\t\t\t\tstyle='display: none; width: 1px; height: 1px' /><img\r\n");
      out.write("\t\t\t\tsrc='");
      out.print(Configuration.cdnprefix);
      out.write("/css/spriter.png' alt=''\r\n");
      out.write("\t\t\t\tstyle='display: none; width: 1px; height: 1px' />\r\n");
      out.write("\t\t\t<div id='mobile'>\r\n");
      out.write("\t\t\t\t<a\r\n");
      out.write("\t\t\t\t\thref='");
      out.print((PageHandler.getInstance(request, response).s != null
							&& PageHandler.getInstance(request, response).s.wineset.knownwineid > 0)
									? "/mwine/"
									: "/m" + (PageHandler.getInstance(request, response).searchdata.getName()
											.length() > 2 ? "?name=" : ""));
      out.print((PageHandler.getInstance(request, response).searchdata.getName().length() > 2
									? Webroutines.URLEncode(
											Webroutines.removeAccents(
													PageHandler.getInstance(request, response).searchdata.getName()))
											+ (PageHandler.getInstance(request, response).searchdata.getVintage()
													.length() > 3
															? "+" + PageHandler.getInstance(request,
																	response).searchdata.getVintage()
															: "").trim()
									: ""));
      out.write("'>Mobile\r\n");
      out.write("\t\t\t\t\taccess</a> <a href='/nf/wine-guide/' rel='nofollow'>Wine Guide</a> <a\r\n");
      out.write("\t\t\t\t\thref='/settings/index.jsp' rel='nofollow'>PriceAlerts</a> <a\r\n");
      out.write("\t\t\t\t\thref='/retailers.jsp'>Getting listed</a> <a href='/about.jsp'\r\n");
      out.write("\t\t\t\t\trel='nofollow'>About us</a> <a href='/links.jsp'>Links</a> <a\r\n");
      out.write("\t\t\t\t\thref='/publishers.jsp' rel='nofollow'>For web site owners</a>\r\n");
      out.write("\t\t\t\t<!-- <a href='/Deals.jsp' rel='nofollow'>Deals</a> -->\r\n");
      out.write("\t\t\t\t");

					if (request.getRemoteUser() != null) {
				
      out.write("<a href='/settings/index.jsp?logoff=true'>Log off</a>\r\n");
      out.write("\t\t\t\t");

					}
				
      out.write("\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t&nbsp;\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t");
      out.write("\r\n");
      out.write("<div class='container'>\r\n");
      out.write("\t");
if (!request.getServerName().contains("searcher")&&(session.getAttribute("fws")==null||!((String)session.getAttribute("fws")).equals("true"))){ 
      out.write("<div class='logo'><a href=\"/\"><img src='");
      out.print(Configuration.cdnprefix);
      out.write("/css2/logo.png' alt='Home page'/></a>");
if (false){ 
      out.write("<div id='plusone'><script type='text/javascript'>/*<![CDATA[*/document.write('<g:plusone href=\"");
      out.print(PageHandler.getInstance(request,response).plusonelink );
      out.write("\"></g:plusone>');/*]]>*/</script></div>");
}} else {session.removeAttribute("fws");	
      out.write("<div class='logofws'><a href=\"https://www.vinopedia.com\"><img src='/css/FWSisnowvinopedia.png' alt='To vinopedia'/></a>");
} 
      out.write("</div>\r\n");
      out.write("\t<div class='clearboth'></div>\r\n");
      out.write("</div>\r\n");
      out.write("<div class=\"bigsearchbackground\">\r\n");
      out.write("<div class=\"bigsearch\">\r\n");
      out.write("\t\t<h1>The world's most powerful search engine for wine</h1>\r\n");
      out.write("\t\t<form action='");
      out.print(PageHandler.getInstance(request,response).searchpage);
      out.write("' method=\"post\" id=\"searchform\" name=\"searchform\" accept-charset=\"UTF-8\"><input type=\"hidden\" name=\"dosearch\" value=\"true\" /><input class='searchinput' id='name' type='text' name=\"name\" value=\"");
      out.print(Webroutines.escape(PageHandler.getInstance(request,response).searchdata.getName()));
      out.write("\" size=\"25\"  /></form>\r\n");
      out.write("\t\t<div class='explanation'>Enter a wine name, store, region or producer name and search in ");
      out.print(Hemabox.getWinecount());
      out.write(" wine offers. <br/>Try our <a style='text-decoration:underline;' href='/wine-guide/'>wine guide</a> if you're not looking for any specific wine, or <a style='text-decoration:underline;' href='/wine-stores/'>find a wine store close to you</a>.</div>\r\n");
      out.write("\t\t<input type='image' class='sprite sprite-searchgo searchgo' src='");
      out.print(Configuration.staticprefix );
      out.write("/images/transparent.gif' onclick='document.getElementById(\"searchform\").submit()' alt='Search'/>\r\n");
      out.write("</div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<div class='textpage'>\r\n");
      out.write("\t\t");

			//<div style='border:3px dashed #4d0027;padding:10px;padding-top:0px;'><h2><font style='color:black;font-size:22px;' face='times, times new roman'>Breaking news! FINANCIAL TIMES: </font></h2><img src='/images/Jancis_Robinson.jpg' alt='Jancis Robinson' style='float:left;padding-right:10px;'/><h2>&#8220;Perhaps the most attractive, user-friendly competitor is Vinopedia.com&#8221;</h2>Jancis Robinson, in an article on Wine Search Engines in the <a href='http://www.ft.com/cms/s/2/121122dc-c1ea-11df-9d90-00144feab49a.html' target='_blank'>Financial Times</a>. Thank you, Jancis, this is the stuff that keeps us going!<br/>"Perhaps the most attractive, user-friendly competitor is Vinopedia.com, set up by Dutch wine lovers Jeroen Starrenburg and Jasper Hammink, who quit their jobs in IT to build a site that locates prices and stockists of 1.6m different wines (the current tally) but also incorporates individual wine ratings (from American wine magazine Wine Spectator). One particularly useful feature is that they identify wines whose prices have dropped most significantly recently and showcase them on their home page." Read the full artice in the <a href='http://www.ft.com/cms/s/2/121122dc-c1ea-11df-9d90-00144feab49a.html' target='_blank'>Financial Times</a> or the <a href='http://www.jancisrobinson.com/articles/a201009173.html' target='_blank'>Purple pages</a>.</div>
		
      out.write("\r\n");
      out.write("\t\t<h1>\r\n");
      out.write("\t\t\tCompare online wine prices with vino<font color='black'>pedia</font>\r\n");
      out.write("\t\t</h1>\r\n");
      out.write("\t\t<br />Vinopedia.com is a wine search engine that helps you to buy\r\n");
      out.write("\t\twine online. We compare the price lists of wine stores world wide,\r\n");
      out.write("\t\tshow you who is selling your favorite wine and who is the cheapest in\r\n");
      out.write("\t\tthe market. Just type (part) of a wine name in the search box to see\r\n");
      out.write("\t\thow it works.<br />We also give you background information of each\r\n");
      out.write("\t\twine, such as ratings, and you can use our <a href='/wine-guide/'>wine\r\n");
      out.write("\t\t\tbuying guide</a> to discover the best wines from a region or a grape\r\n");
      out.write("\t\tvariety, based on price and quality.<br /> <br />\r\n");
      out.write("\t\t");
      out.print(Webroutines.getConfigKey("systemmessage"));
      out.write("\r\n");
      out.write("\t\t<div\r\n");
      out.write("\t\t\tstyle='border: 3px dashed #4d0027; padding: 10px; padding-top: 0px; height: 320px; width: 45%; float: left'>\r\n");
      out.write("\t\t\t<a\r\n");
      out.write("\t\t\t\thref='https://itunes.apple.com/us/app/vinopedia.com/id668028831?mt=8'\r\n");
      out.write("\t\t\t\ttitle='Vinopedia iPhone app'><img\r\n");
      out.write("\t\t\t\tstyle='margin-right: 20px; width: 128px; height: 184px; float: right; margin: 10px; margin-top: 20px'\r\n");
      out.write("\t\t\t\tsrc='");
      out.print(Configuration.staticprefix);
      out.write("/images/iphoneapp.jpg'\r\n");
      out.write("\t\t\t\talt='Vinopedia iPhone app' /></a><a\r\n");
      out.write("\t\t\t\thref='https://itunes.apple.com/us/app/vinopedia.com/id668028831?mt=8'\r\n");
      out.write("\t\t\t\ttitle='Vinopedia iPhone app'><img\r\n");
      out.write("\t\t\t\tstyle='margin: 10px; width: 135px; height: 40px; float: right; clear: right;'\r\n");
      out.write("\t\t\t\tsrc='");
      out.print(Configuration.staticprefix);
      out.write("/images/Download_on_the_App_Store_Badge_US-UK_135x40.png'\r\n");
      out.write("\t\t\t\talt='Vinopedia iPhone app' /></a>\r\n");
      out.write("\t\t\t<h2>\r\n");
      out.write("\t\t\t\tNew: <a\r\n");
      out.write("\t\t\t\t\thref='https://itunes.apple.com/us/app/vinopedia.com/id668028831?mt=8'\r\n");
      out.write("\t\t\t\t\ttitle='Vinopedia iPhone app'>Vinopedia iPhone app</a>\r\n");
      out.write("\t\t\t</h2>\r\n");
      out.write("\t\t\tWe just released the Vinopedia app for iPhone. With this app you can\r\n");
      out.write("\t\t\teasily search through millions of wine offers from 4200 online wine\r\n");
      out.write("\t\t\tstores indexed by vinopedia.com from your iPhone. At home after you\r\n");
      out.write("\t\t\tfinished the bottle you wish you had more. In a restaurant when you\r\n");
      out.write("\t\t\twonder if the price is reasonable. Or at the winery to find out if\r\n");
      out.write("\t\t\tstores nearby your home offer this wine. Vinopedia will direct you to\r\n");
      out.write("\t\t\tthe store page of the wine offer you selected, or you can have it\r\n");
      out.write("\t\t\tsent to your email account in case you prefer to order it from your\r\n");
      out.write("\t\t\thome computer.\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div\r\n");
      out.write("\t\t\tstyle='border: 3px dashed #4d0027; padding: 10px; padding-top: 0px; height: 320px; width: 45%; float: right'>\r\n");
      out.write("\t\t\t<h2>\r\n");
      out.write("\t\t\t\t<a href='/plugins/' title='Browser extension'>Vinopedia Browser\r\n");
      out.write("\t\t\t\t\tPlugin</a>\r\n");
      out.write("\t\t\t</h2>\r\n");
      out.write("\t\t\tGet the plugin for your browser that lets you quickly check the price\r\n");
      out.write("\t\t\tof any wine from anywhere on the web. Just highlight (select) a wine\r\n");
      out.write("\t\t\ton any page, select \"Find on Vinopedia\" from the menu and a new page\r\n");
      out.write("\t\t\topens with the pricing information of the wine you selected. Saving\r\n");
      out.write("\t\t\tmoney has never been easier! You can now install the tool from the <a\r\n");
      out.write("\t\t\t\thref='/plugins/' title='Browser extension'>browser plugin</a> page.\r\n");
      out.write("\t\t\tGo ahead and try it out!<br /> <a href='/plugins/'\r\n");
      out.write("\t\t\t\ttitle='Browser extension'><img\r\n");
      out.write("\t\t\t\tstyle='margin-right: 20px; width: 300px; height: 150px'\r\n");
      out.write("\t\t\t\tsrc='");
      out.print(Configuration.staticprefix);
      out.write("/images/extensions.gif'\r\n");
      out.write("\t\t\t\talt='Browser Plugin' /></a>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div style='clear: both'>\r\n");
      out.write("\t\t\t<div>\r\n");
      out.write("\t\t\t\t<h2>\r\n");
      out.write("\t\t\t\t\t<a href='/wine-stores/'>Wine Stores</a>\r\n");
      out.write("\t\t\t\t</h2>\r\n");
      out.write("\t\t\t\tShows a map of wine stores close to you and interesting new wines\r\n");
      out.write("\t\t\t\tthey got in the last week.\r\n");
      out.write("\t\t\t\t");
      out.write("\r\n");
      out.write("<a name=\"tips\"></a><div class='tips'>\r\n");
      out.write("<h2>");
      out.print(PageHandler.getInstance(request,response).t.get("todaystips"));
if (!PageHandler.getInstance(request,response).thispage.contains("/tips.jsp")) {
      out.write("  <span class='small'>(view <a href='/tips.jsp'>all price drops</a> here)</span>");
} 
      out.write("</h2>\r\n");
      out.write("<p>");
      out.print(PageHandler.getInstance(request,response).t.get("tiptext"));
      out.write("</p>\r\n");
      out.write("\t\t\t");

			String tips=(Webroutines.getTipsHTML3("", 8,PageHandler.getInstance(request,response).searchdata));
			out.print(tips.equals("") ? ("<br />" + PageHandler.getInstance(request,response).t.get("notips")):(tips));
      out.write('\r');
      out.write('\n');
 if (!PageHandler.getInstance(request,response).thispage.contains("/tips.jsp")){
      out.write('\r');
      out.write('\n');
} 
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.print(Hemabox.getHtml(p));
 
	PageHandler.getInstance(request,response).getLogger().logaction();
	session.setAttribute("lasturl",PageHandler.getInstance(request,response).thispage);
	String canonicallink=(String)request.getAttribute("canonicallink");
	String regionlink=(String)request.getAttribute("regionlink");
	if (regionlink==null) regionlink="<a href='/region/'>Wines by region</a>";

      out.write("<div class='footer'><div id='links'><a href='/' rel='nofollow'>Home</a><a href='/links.jsp' rel='nofollow'>Links</a><a href='/contact.jsp' rel='nofollow'>Contact Vinopedia</a><a href='/about.jsp' rel='nofollow'>About us</a><a href='/termsofuse.jsp' rel='nofollow'>Terms of use</a>");
      out.print(regionlink);
 if (canonicallink!=null) out.write("<br/>"+canonicallink); 
      out.write("</div>\r\n");
      out.write("<div class='clear'></div><div id='copyright'>&#169; ");
      out.print(java.util.GregorianCalendar.getInstance().get(java.util.GregorianCalendar.YEAR));
      out.write(" Vinopedia.com</div></div>");

PageHandler.getInstance(request,response).firstrequest=false;
PageHandler.getInstance(request,response).cleanup();
//for (Cookie cookie:request.getCookies()) { 
//	if (cookie.getName().equals("wineid")||cookie.getName().equals("sort")||cookie.getName().equals("vintage")) {cookie.setMaxAge(0);response.addCookie(cookie);}
//}
 
      out.write("</div>\r\n");
      out.write("\t\t\t<!--  mainwide-->\r\n");
      out.write("\t\t\t");

				} else {
						pl.log("Start ads");
						String bannersshown = "";
						//RecommendationAd ra=new RecommendationAd(p.s.wineset.bestknownwineid,p.searchdata.getLastcountry());
						String rightadhtml = "";//ra.getAd(p,"Winead");
						if (rightadhtml.equals("")) {
							pl.log("Got no recommendadtion ad, try again");
							Ad newad = new Ad(p.bot, "winered", 160, 600, p.hostcountry, p.s.wineset.region,
									p.s.wineset.bestknownwineid, "");
							bannersshown = newad.bannersshown;
							rightadhtml = newad.html;
							pl.log("Got right ad");
						} else {
							pl.log("Got recommendation ad");
						}

						//Show search results
			
      out.write('\r');
      out.write('\n');
 //PageHandler p=(PageHandler)request.getAttribute("pagehandler");
      out.write('\r');
      out.write('\n');
 String mobilelink="/m";
 if (PageHandler.getInstance(request,response).thispage.contains("/wine/")){
	 mobilelink=PageHandler.getInstance(request,response).thispage.replace("/wine/","/mwine/");
 } else if (PageHandler.getInstance(request,response).thispage.contains("/winery/")){
	 mobilelink=PageHandler.getInstance(request,response).thispage.replace("/winery/","/mwinery/");
 } else if (PageHandler.getInstance(request,response).thispage.contains("/region/")){
	 mobilelink=PageHandler.getInstance(request,response).thispage.replace("/region/","/mregion/");
 } else {
	mobilelink="/mobile.jsp"+(PageHandler.getInstance(request,response).searchdata.getName().length()>2?"?name="+Webroutines.URLEncode(Webroutines.removeAccents(PageHandler.getInstance(request,response).searchdata.getName()))+(PageHandler.getInstance(request,response).searchdata.getVintage().length()>3?"+"+PageHandler.getInstance(request,response).searchdata.getVintage():"").trim():"");
 }

      out.write("\r\n");
      out.write("<div class='topbar spriter spriter-refine'>\r\n");
      out.write("<div class='topbarcontent'><img src='");
      out.print(Configuration.static2prefix );
      out.write("/css/sprite4.png' style='display:none;width:1px;height:1px' alt=''/><img src='");
      out.print(Configuration.cdnprefix );
      out.write("/css/spriter.png' style='display:none;width:1px;height:1px' alt=''/>\r\n");
      out.write("<div id='mobile'>\r\n");
      out.write("<a href=\"");
      out.print(mobilelink);
      out.write("\">Mobile access</a>\r\n");
      out.write("<a href='");
      out.print((request.getAttribute("wineguidelink")==null?"/nf/wine-guide/":request.getAttribute("wineguidelink")));
      out.write("' rel='nofollow'>Wine Guide</a>\r\n");
      out.write("<a href='/settings/index.jsp' rel='nofollow'>PriceAlerts</a>\r\n");
      out.write("<a href='/retailers.jsp' rel='nofollow'>Getting listed</a>\r\n");
      out.write("<a href='/about.jsp' rel='nofollow'>About us</a>\r\n");
      out.write("<a href='/links.jsp' rel='nofollow'>Links</a>\r\n");
      out.write("<a href='/publishers.jsp' rel='nofollow'>For web site owners</a>\r\n");
      out.write("<!-- <a href='/Deals.jsp' rel='nofollow'>Deals</a> -->\r\n");
if (request.getRemoteUser()!=null) {
      out.write("<a href='/settings/index.jsp?logoff=true'>Log off</a>");
} 
      out.write("\r\n");
      out.write("</div>\r\n");
if (false){ 
      out.write("\r\n");
      out.write("<!-- \r\n");
      out.write("<div id='language'>");
      out.print(PageHandler.getInstance(request,response).t.get("language"));
      out.write(": \r\n");
      out.write("<a href='/lang-EN/wine/");
      out.print((Webroutines.URLEncode(PageHandler.getInstance(request,response).searchdata.getName()).replace("'","&apos;")+(PageHandler.getInstance(request,response).searchdata.getVintage().length()>3?"?vintage=" + PageHandler.getInstance(request,response).searchdata.getVintage():"")));
      out.write("'><img alt='English' src='/images/transparent.gif' class='sprite sprite-language sprite-english'/></a>\r\n");
      out.write("<a href='/lang-FR/wine/");
      out.print((Webroutines.URLEncode(PageHandler.getInstance(request,response).searchdata.getName()).replace("'","&apos;")+(PageHandler.getInstance(request,response).searchdata.getVintage().length()>3?"?vintage=" + PageHandler.getInstance(request,response).searchdata.getVintage():"")));
      out.write("'><img alt='Français' src='/images/transparent.gif' class='sprite sprite-language sprite-french'/></a>\r\n");
      out.write("<a href='/lang-NL/wine/");
      out.print((Webroutines.URLEncode(PageHandler.getInstance(request,response).searchdata.getName()).replace("'","&apos;")+(PageHandler.getInstance(request,response).searchdata.getVintage().length()>3?"?vintage=" + PageHandler.getInstance(request,response).searchdata.getVintage():"")));
      out.write("'><img alt='Nederlands' src='/images/transparent.gif' class='sprite sprite-language sprite-dutch'/></a>\r\n");
      out.write("</div>\r\n");
      out.write(" -->");
} 
      out.write("\r\n");
      out.write("&nbsp;\r\n");
      out.write("</div>\r\n");
      out.write("</div>");
      out.write("<div\r\n");
      out.write("\t\t\t\tclass='container'>");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<div class='logoandsearch' id='logoandsearch'>\r\n");
      out.write("\t\t<div class='logo'><a href=\"/\" title=\"Wine Searcher and Wine Prices Comparison\"><img src='");
      out.print(Configuration.cdnprefix);
      out.write("/css2/logo.png' alt='Vinopedia Wine Searcher and Price Comparison'/></a></div>\r\n");
      out.write("\t\t<div class='search'>\r\n");
      out.write("\t\t<div class='findwine'>");
      out.print(PageHandler.getInstance(request,response).t.get("searchwine"));
      out.write("</div>\r\n");
      out.write("\t\t\t");
// <img class='searchgosmall' alt='Search' src='/css2/gosmall.jpg' onclick='document.getElementById("searchform").submit()' />
      out.write("\r\n");
      out.write("\t\t\t<form action='");
      out.print(PageHandler.getInstance(request,response).searchpage);
      out.write("' method=\"post\" id=\"searchform\" name=\"searchform\" accept-charset=\"UTF-8\"><input type=\"hidden\" name=\"dosearch\" value=\"true\" /><input class='searchinput' id='name' type='text' name=\"name\" value=\"");
      out.print(Webroutines.escape((PageHandler.getInstance(request,response).searchdata.getName()+" "+PageHandler.getInstance(request,response).searchdata.getVintage()).trim()));
      out.write("\" size=\"25\" /></form>\r\n");
      out.write("\t\t\t<div class='sprite sprite-gosmall searchgosmall' onclick='document.getElementById(\"searchform\").submit()' ></div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("</div>\r\n");
 // <div id='plusone'><script type='text/javascript' defer="defer">/*<![CDATA[*/document.write('<g:plusone href="<%=PageHandler.getInstance(request,response).plusonelink % >"></g:plusone>');/*]]>*/</script></div>

      out.print(Webroutines.getConfigKey("systemmessage"));
      out.write("</div>\r\n");
      out.write("\t\t\t");

				pl.log("Start rating");
			
      out.write("\r\n");
      out.write("\t\t\t");

				Webroutines.RatingInfo ri = null;
						if (p.s.singlevintage > 0 && p.s.wineset.records > 0) {
							out.print(Webroutines.getWineInfo(p.s.wineset.bestknownwineid, p.s.singlevintage, p));
						} else {
							ri = Webroutines.getRatingsMicroformatHTML(p, p.s.wineset.bestknownwineid, 1000, p.searchpage,
									p.s.singlevintage, p.searchdata, p.t, request.isUserInRole("admin"));
							out.print(ri.html);
							pl.log("Getting banners");
							Ad adbetween = new Ad(p.bot, "winered", 1000, 60, p.hostcountry, p.s.wineset.region,
									p.s.wineset.bestknownwineid, "");
							pl.log("Got banners");
							out.print(adbetween.html);
							if (!p.bot)
								p.getLogger().setBannersshown(adbetween.bannersshown + bannersshown);
						}
			
      out.write("<div class='main'>\r\n");
      out.write("\t\t\t\t<div id='adright'>\r\n");
      out.write("\t\t\t\t\t");

						out.write(rightadhtml);
					
      out.write("\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div id='mainleft'>\r\n");
      out.write("\t\t\t\t\t<noscript>\r\n");
      out.write("\t\t\t\t\t\t<img src='/images/nojs.gif' alt='' />\r\n");
      out.write("\t\t\t\t\t</noscript>\r\n");
      out.write("\t\t\t\t\t");

						pl.log("Start results");
					
      out.write("\r\n");
      out.write("\t\t\t\t\t");
      out.print(Webroutines.getTabbedWineResultsHTML(p.s.wineset, p.getTranslator(), p.searchdata, 25,
							response, "true", true, p.searchpage, p.s.singlevintage, ri, false,
							request.isUserInRole("admin")));
      out.write("\r\n");
      out.write("\t\t\t\t\t<div class='pricenote'>");
      out.print(p.getTranslator().get("pricenote"));
      out.write("</div>\r\n");
      out.write("\t\t\t\t\t");

						pl.log("Start footer");
					
      out.write("\r\n");
      out.write("\t\t\t\t\t");

						//if (p.s.wineset.region!=null&&p.s.wineset.region.length()>1) request.setAttribute("regionlink","<a href='/region/"+Webroutines.removeAccents(p.s.wineset.region).replaceAll(", ","/").replaceAll("'","&apos;").replaceAll(" ","+")+"/'>"+(p.s.wineset.region.split(", ")[p.s.wineset.region.split(", ").length-1])+" information</a>");
					
      out.write("\r\n");
      out.write("\t\t\t\t\t");

						out.print(Webroutines.getSpecialPageLinks(p.searchdata.getName()));
								pl.log("Finished");

								if (System.currentTimeMillis() - p.getLogger().startload > 10000) {
									Dbutil.logger.info("Long load time for index.jsp. Loadtime: "
											+ (System.currentTimeMillis() - p.getLogger().startload) + ". Log:" + pl.getLog());

								}
					
 
	PageHandler.getInstance(request,response).getLogger().logaction();
	session.setAttribute("lasturl",PageHandler.getInstance(request,response).thispage);
	String canonicallink=(String)request.getAttribute("canonicallink");
	String regionlink=(String)request.getAttribute("regionlink");
	if (regionlink==null) regionlink="<a href='/region/'>Wines by region</a>";

      out.write("<div class='footer'><div id='links'><a href='/' rel='nofollow'>Home</a><a href='/links.jsp' rel='nofollow'>Links</a><a href='/contact.jsp' rel='nofollow'>Contact Vinopedia</a><a href='/about.jsp' rel='nofollow'>About us</a><a href='/termsofuse.jsp' rel='nofollow'>Terms of use</a>");
      out.print(regionlink);
 if (canonicallink!=null) out.write("<br/>"+canonicallink); 
      out.write("</div>\r\n");
      out.write("<div class='clear'></div><div id='copyright'>&#169; ");
      out.print(java.util.GregorianCalendar.getInstance().get(java.util.GregorianCalendar.YEAR));
      out.write(" Vinopedia.com</div></div>");

PageHandler.getInstance(request,response).firstrequest=false;
PageHandler.getInstance(request,response).cleanup();
//for (Cookie cookie:request.getCookies()) { 
//	if (cookie.getName().equals("wineid")||cookie.getName().equals("sort")||cookie.getName().equals("vintage")) {cookie.setMaxAge(0);response.addCookie(cookie);}
//}
 
      out.write("\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t");

				// workaround: IE positioning of footer
			
      out.write("\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t");

			if ("sneak preview".equalsIgnoreCase(p.searchdata.getName()))
						out.write(
								"<br/><br/><h1>Test modus geactiveerd. </h1><h2>Om terug te gaan naar normale modus, sluit je browser helemaal af en keer terug naar Vinopedia.com</h2>Opmerkingen, fouten, etc. graag terugmelden aan <a style='text-decoration:underline;' href='mailto:feedback@vinopedia.com'>feedback@vinopedia.com</a>. <br/><br/>Bedankt, Jasper");
		
      out.write("\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<!--  main-->\r\n");
      out.write("\t");

		}
		}
	
      out.write("\r\n");
      out.write("\t<script type=\"text/javascript\">\r\n");
      out.write("\t\t$(document).ready(function() {\r\n");
      out.write("\t\t\tsetTimeout(function() {\r\n");
      out.write("\t\t\t\tinitSmartSuggest();\r\n");
      out.write("\t\t\t}, 1500)\r\n");
      out.write("\t\t});\r\n");
      out.write("\t</script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
