/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.105
 * Generated at: 2020-09-08 07:26:19 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.admin;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.text.SimpleDateFormat;

public final class adminlinks_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<a href=\"/moderator/index.jsp\">Moderator menu</a><br/>\r\n");
      out.write("<a href=\"index.jsp\">Admin overview</a><br/>\r\n");
      out.write("<a href=\"visitoroverview.jsp\">Visitors overview</a><br/>\r\n");
      out.write("<a href=\"");
      out.print( response.encodeURL("referrers.jsp"));
      out.write("\">Referrers</a><br/>\r\n");
      out.write("<a href=\"");
      out.print( response.encodeURL("top50.jsp"));
      out.write("\">Top 50 lists</a><br/>\r\n");
      out.write("<a href=\"");
      out.print( response.encodeURL("addautodiscovershop.jsp"));
      out.write("\">Automatically discover a new URL</a><br/>\r\n");
      out.write("<a href=\"");
      out.print( response.encodeURL("autoshopoverview.jsp"));
      out.write("\">View Automatically discovered shops</a><br/>\r\n");
      out.write("<a href=\"");
      out.print( response.encodeURL("/moderator/index.jsp"));
      out.write("\">Manage shops and spiders</a><br/>\r\n");
      out.write("<a href=\"");
      out.print( response.encodeURL("taskrunner.jsp"));
      out.write("\">Admin Task Runner</a><br/>\r\n");
      out.write("<a href=\"/log/vinopediaBatch.log\">View batch logging</a><br/>\r\n");
      out.write("<a href=\"/log/tomcat.log\">View Tomcat logging</a><br/>\r\n");
      out.write("<a href=\"");
      out.print( response.encodeURL("/admin/useractivity.jsp"));
      out.write("\">Check/rollback community changes</a><br/>\r\n");
      out.write("<a href=\"");
      out.print( response.encodeURL("/admin/ai/"));
      out.write("\">Knownwine tools</a><br/>\r\n");
      out.write("<a href=\"");
      out.print( response.encodeURL("/admin/salesdashboard.jsp"));
      out.write("\">Sales dashboard</a><br/>\r\n");
      out.write("<a href=\"");
      out.print( response.encodeURL("/admin/sponsors.jsp"));
      out.write("\">Sponsor overview</a><br/>\r\n");
      out.write("<a href=\"");
      out.print( response.encodeURL("/admin/financedashboard.jsp"));
      out.write("\">Finance dashboard</a><br/>\r\n");
      out.write("<a href='countryoverview.jsp'>Country overview of wines and shops</a><br/>\r\n");
      out.write("<a href='sendstoreinvitations.jsp'>Send mailing to stores</a><br/>\r\n");
      out.write("<a href='winerymailing.jsp'>Send mailing to wineries</a><br/>\r\n");
      out.write("<a href='usatodo.jsp'>To do list USA stores</a><br/> \r\n");
      out.write("<a href='/admin/monitor.jsp?interval=15'>Activity Monitor</a><br/>\r\n");
      out.write("<a href='/admin/createpayment.jsp'>Create payment link</a><br/>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
